### ISSUE TITLE
[Bug]: attempt to call field 'getScissor' (a nil value)

### ISSUE THREAD

**Issue by NyakoFox** [lovebrew/lovepotion#206] opened 2023-09-28 18:55 UTC
### Software Version

3.0 Pre-Release 5

### What Happened?

Looks like `love.graphics.getScissor()` doesn't exist in 3.0, despite existing in older versions.

### What was Expected?

I expected the function to uh, exist.

### Code to Reproduce

```Lua
`print(love.graphics.getScissor)` = `nil`
```

### Console

Nintendo Switch

### Firmware Version(s)

16.1.0

### Custom Firmware Version

1.5.5

### Execution Method

Homebrew Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment] 2023-09-28 19:05
Yeah this is one of those times where I probably have it implemented in the code base, just not hooked up. I'll double check that when I can, but I'll definitely put it in for the next prerelease since I'm planning on doing one soon.

Thanks for letting me know!

**Comment by TurtleP** [comment] 2023-09-28 19:06
In the meantime, you could probably manually keep track of the scissor(s) and their bounds. It's not ideal, but at least something for now.

**Comment by NyakoFox** [comment] 2023-09-28 19:06
Yep, thankfully I already wrap most graphics functions so it's pretty easy to implement 😄

**Comment by TurtleP** [comment] 2023-09-28 19:10
If there's any other things I missed, do let me know. I try to not miss things, but it gets harder as time goes on ;)

**Comment by NyakoFox** [comment] 2023-09-28 19:38
- I noticed there's like, `love.window` stuff missing, like `getIcon`, `getTitle`, `setVSync`, etc. but that makes sense to not have.

- `love.keyboard.isDown` seems to be missing! It almost doesn't make sense to include anyway, but I think the switch lets you plug in a keyboard, like the wii allowed?

- `love.graphics.setCanvas` doesn't seem to be able to take a table as input, though I didn't end up needing it anyway, so that got stripped from my code. Nothing crucial, just thought I'd mention it.

That's all I've noticed so far, I'm currently trying to debug a system crash from my project (kinda just putting `print`s everywhere) but once that's done I'll make sure to let you know if I run into anything else. I love this project by the way :D

**Comment by TurtleP** [comment] 2023-09-28 19:41
> love.keyboard.isDown seems to be missing! It almost doesn't make sense to include anyway, but I think the switch lets you plug in a keyboard, like the wii allowed?

What I understand is yeah, you can, but I don't see a point because you should be more developing for the console than as if you were still on a computer. Which I guess is a stupid take, but ¯\_(ツ)_/¯. I can at the very least allow it to be defined, but then libraries like baton won't work as expected.

> love.graphics.setCanvas doesn't seem to be able to take a table as input, though I didn't end up needing it anyway, so that got stripped from my code. Nothing crucial, just thought I'd mention it.

Hmm I may have skipped that part of the reimplementation - which is why it wouldn't work, but also this _is_ based on LÖVE 12, so it's probably different than 11.4.

**Comment by NyakoFox** [comment] 2023-09-28 20:04
By the way, it looks like `print`s inside of threads don't get picked up by the debugger system. (I'm using the `next` branch of nestlink, since that seems to be what's compatible with 3.0)

**Comment by TurtleP** [comment] 2023-09-28 20:10
Interesting note, will take a look when I can, sometime.

**Comment by NyakoFox** [comment] 2023-09-28 20:25
Sorry for using this issue as a discussion form, I swear this is my last question; does pushing to threads work properly in 3.0? It seems like a `:push("test")` is hanging the main thread in my code (according to the debug prints, anyway)

**Comment by TurtleP** [comment] 2023-09-28 20:30
Yeah there's a bug with Channels right now, which will be fixed once I get the next prerelease out. Alternatively, there *are* nightly [builds of 3.0 with the fix](https://github.com/lovebrew/lovepotion/actions). Ignore the disabled LÖVE Potion action, that's old. Looks like you'll want the Nintendo Switch action.

**Comment by NyakoFox** [comment] 2023-09-28 21:00
Hmm, `love.graphics.clear(0, 0, 0, 1)` seems to be crashing the whole system.

**Comment by TurtleP** [comment] 2023-09-28 21:03
That doesn't seem relevant since this is called every frame. I'd need to know what you're doing specifically code-wise to know the root cause. If you'd like, hop onto the Discord and we can discuss that there.

**Comment by TurtleP** [comment] 2023-10-12 13:31
This should be fixed (original title) with #210

**Closed by TurtleP** 2023-10-12 13:31 UTC
Labels: bug
