### ISSUE TITLE
[Bug]: 3.0.1 crashes WiiU when launching

### ISSUE THREAD

**Issue by rush-treble** [lovebrew/lovepotion#229] opened 2024-05-27 17:09 UTC
### Software Version

3.0.1

### What Happened?

Crashes the WiiU when attempting to launch via the WiiU menu. Need to hold down the power button to shut it down, stuck on the LovePotion icon that is shown when loading up any WiiU menu app. I couldn't find any logs to indicate why it crashed, maybe they exist but I don't know where they are, sorry

3.0 works as far as not crashing the WiiU goes.

I tried both stable 3.0.1 and the latest commit, both crash

### What was Expected?

No crashing, game attempts to load.

### Code to Reproduce

```Lua
-- any code, does not get to the point of loading your main.lua --
```

### Console

Nintendo Wii U

### Firmware Version(s)

5.5.6U

### Custom Firmware Version

Aroma 5-10-24

### Execution Method

Wii U Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by Nawias** [comment] 2024-05-27 19:17
This looks like the same issue I have. What region is your console?

**Comment by rush-treble** [comment] 2024-05-27 22:45
> This looks like the same issue I have. What region is your console?

USA, 5.5.6U according to the system settings menu

**Comment by playsamay4** [comment] 2024-06-14 18:51
same here, 5.5.6U

**Comment by TurtleP** [comment] 2024-06-14 18:58
The best way to help me debug this is if you grab your logs from slc on the console.

When connected via ftp, navigate to `storage_slc/sys/logs` and download the log file(s) there. I only need the latest one from there.

**Comment by playsamay4** [comment] 2024-06-14 19:29
here's the latest dated log after the crash
[18.log](https://github.com/user-attachments/files/15842679/18.log)

**Comment by TurtleP** [comment] 2024-06-14 19:36
It looks like Freetype is trying to create a new font face, but why it's crashing I'm not entirely sure. I double checked the default font data and it seems fine. I'll keep looking.

**Comment by TurtleP** [comment] 2024-06-14 19:58
Okay root cause found: apparently the font module had its *own* `FT_Library` variable which was used instead of the base class's. Just need to fix one other thing and it should be fine.

**Comment by TurtleP** [comment] 2024-08-12 16:19
Closing in favor of opening a new issue relevant to the regression mentioned in #232.

**Closed by TurtleP** 2024-08-12 16:19 UTC
Labels: bug
