### ISSUE TITLE
[BUG] Pixels misaligned when drawing textures, quads or text

### ISSUE THREAD

**Issue by Nehemek** [lovebrew/LovePotion#131] opened 2021-04-04 06:12 UTC
### **Describe the bug**
When drawing textures, quads or text, they are misaligned with the _real_ pixels of the screen causing artifacts to appear. This is particularly noticeable with pixel perfect elements (i.e. pixel art).

### **Expected behavior**
Drawables should align properly with the screen pixels unless offset by a transformation or the x,y arguments of their respective functions.

### **Relevant Code To Reproduce**
This image file can be used to test the issue: 
![demotexture](https://user-images.githubusercontent.com/66986051/113500383-bb3c3a80-94da-11eb-9aa0-04bf1ef6a2fb.png)
Some of the artifacts produced are shown in the screenshot below.

For the print functions, the font Digital Disco can be used to test. Load at 15 pixels to get it to display pixel perfect: https://www.dafont.com/digital-disco.font

### **[Screenshots]**
![misaligned](https://user-images.githubusercontent.com/66986051/113500097-a2cb2080-94d8-11eb-95fa-928361469ea4.png)

### **System Info [Please complete the following information]:**
System: 3ds v11.14.0-46U
CFW: Luma v10.2.1
Method of execution: Homebrew App
LÖVE Potion version: 2.0.0

**Comment by TurtleP** [comment] 2021-04-06 00:53
Sorry for the delay in response. I'm not exactly sure what to tell you here. It might just be the way the sprites get handled when rendered. I think there's some level of this happening in normal LÖVE as well, though much less noticeable.

Either way, I'll try to talk with the maintainer of citro2d about this, but it'll likely be a non-issue which can't be fixed I think.

**Comment by Nehemek** [comment] 2021-04-12 02:12
After some experimentation it appears that the issue is that the draw functions scale things slightly up. After some experimentation I have found that drawing elements at .982 scale (to compensate) produce the most accuarate results to the source image or canvas (albeit it is still not 100% correct). This is quite strange.

**Comment by TurtleP** [comment] 2021-04-12 16:59
Discussion with others about this issue is currently taking place. The root cause has been identified, but the solution hasn't been found *yet*. Hopefully it's not too crazy.

**Comment by TurtleP** [comment] 2021-04-13 07:03
Fixed in ab69af7 -- requires a new tex3ds release as well

**Closed by TurtleP** 2021-04-13 07:03 UTC
Labels: 3DS, bug
